<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BwfAlternateModel\Module'   => __DIR__ . '/Module.php',
    'BwfAlternateModel\CsvModel' => __DIR__ . '/src/BwfAlternateModel/CsvModel.php',
    'BwfAlternateModel\PdfModel' => __DIR__ . '/src/BwfAlternateModel/PdfModel.php',
);